### ISSUE TITLE
./run-clang-tidy.py no such file or directory

### ISSUE THREAD

**Issue by ThisALV** [HorstBaerbel/action-clang-tidy#1]
I'm getting this error at "Run clang-tidy" step :

```
-- The CXX compiler identification is GNU 8.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /github/workspace/build
python3: can't open file './run-clang-tidy.py': [Errno 2] No such file or directory
```

Here is my clang-tidy.yml config file :

```yaml
name: Clang-tidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Cland-Tidy linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run clang-tidy
        uses: HorstBaerbel/action-clang-tidy@1.0
```

Any ideas about the cause of this problem ?
